services:
  gazebo-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_arm_ai_gazebo_vnc
    ports:
      - "6180:6080"
      - "5901:5900"
      - "11312:11311"
    environment:
      - DISPLAY=:1
    shm_size: "1gb"
    restart: unless-stopped
    volumes:
      - ./gazebo_home:/root/.gazebo
      - ./saved_worlds:/saved_worlds

